### PR TITLE
[CMake] Add minimal cmake file

### PR DESCRIPTION
**Pull request by Mike-Devel**
Generate cmake target that can
be used by other libraries to express their dependency on
this library and retrieve any configuration information
such as the include directory, transitive dependencies,
necessary compiler options or the required c++ standards level.

### CODE REVIEW

**Comment by eldiener** [comment]
I need a test, which can be invoked using the b2 framework which Boost currently uses to run tests for each library, which shows this PR actually working in a CMake project. I would heavily prefer the test to be one of the tests in the vmd test jamfile and not in some overall Boost jamfile because it is important to run such a test as part of vmd testing to verify that this PR actually works.

**Comment by Mike-Devel** [comment]
Fair enough. Is there a good tutorial on how to execute a bunch of shell commands from a b2 test?

**Comment by eldiener** [comment]
I do not think there is a tutorial but I believe there is a way to call the command processor to execute a batch file on Windows or a shell program on Linux. I am not sure what the Mac has as far as batch processing.

**Comment by Mike-Devel** [comment]
However, as this library has a dependency on boost::preprocessor you can't test it without that library being present and having a cmake file too (at least in order to be realistic).

**Comment by eldiener** [comment]
Regarding the boost::preprocessor library being present isn't CMake responsible for finding that library when the proper CMakeLists.txt exists for boost::preprocessor ? Regarding the cmake file for boost::preprocessor I have already answered in the PR you created there that I need a test in preprocessor which verifies the correctness of the PR in order to accept the PR there.

**Comment by Mike-Devel** [comment]
> Regarding the boost::preprocessor library being present isn't CMake responsible for finding that library when the proper CMakeLists.txt exists for boost::preprocessor ? 

Isn't that what I said? I just wanted to point ot that there is a dependency in car this wasn't clear. 

> Regarding the cmake file for boost::preprocessor I have already answered in the PR you created there that I need a test in preprocessor which verifies the correctness of the PR in order to accept the PR there.

I know.  I just didn't answer there, as it would have been pretty much the same as here.

**Comment by eldiener** [comment]
I have merged your PR to add your CMake files for preprocessor so if you can likewise provide a test for VMD I would merge your PR for VMD.

**Comment by Mike-Devel** [comment]
Yes, Sorry I should have mentioned I'm not done yet. I'm currently testing the latest changes on a separate branch and will notify them when I incorporated them here.

**Comment by Mike-Devel** [comment]
Btw.: Did you have time to give the changes a look? I made some structureal changes compared to the test in preprocessor test. 
E.g. the CMakeLists.txt file that defines the dummy project using Boost::vmd resides in a separate subdirectory in test. This is to avoid people expecting the file to run the boost vmd unit tests (conventionally that is done from a CMakeLists.txt file that gets called from the vmd root file and located in vmd/test.

Also, just as in boost preprocessor, the changes I made to travis and particular appveyor.yml are somewhat invasive. I'm not an expert in those, so there might be a more elegant way to achieve the same result.

**Comment by Mike-Devel** [comment]
@eldiener: OK, Everything should be fine now (travis had some issues today, which is why it took me much longer than expected). If you are ok with the changes, you can merge the PR once travis is green.

**Pull request merged**
